version: '3'

services:
  mango_api:
    build: .
    ports:
      - "5002:3000"
    depends_on:
      - mango_db
    environment:
      - MONGODB_URI=mongodb://mango_db:27017/ctfDB

  mango_db:
    image: mongo
    ports:
      - "27017:27017"
